name: Build / Sync

on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-8)
          if [ "$GITHUB_REF_TYPE" == "tag" ]; then
            IMAGE_TAG=$GITHUB_REF_NAME
          fi
          echo "Build with tag $IMAGE_TAG"
          
  sync:
    name: Sync
    uses: khanh-bnm/common-workflows/.github/workflows/sync.yaml@main
    continue-on-error: true
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        service:
          - service
          - service-worker
    with:
      service: ${{ matrix.service }}