on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    if: ${{ github.event.label.name == 'review' }}
    runs-on: ubuntu-22.04
    steps:
      - run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-8)
          if [ "$GITHUB_REF_TYPE" == "tag" ]; then
            IMAGE_TAG=$GITHUB_REF_NAME
          fi
          echo "Build with tag $IMAGE_TAG"
  review-start:
    needs: build
    environment:
      name: review
      url: https://pr-sample-${{ github.event.pull_request.number }}.review.example.com
    steps:
      - run: echo "running"