on:
  pull_request:
    branches:
      - 'review/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-8)
          if [ "$GITHUB_REF_TYPE" == "tag" ]; then
            IMAGE_TAG=$GITHUB_REF_NAME
          fi
          echo "Build with tag $IMAGE_TAG"
  review-start:
    needs: build
    environment:
      name: ${{ env.GITHUB_REF_NAME }}
    steps:
      - run: echo "running"